### ISSUE TITLE
confidence interval argument not passed to predict function

### ISSUE THREAD

**Issue by sahirbhatnagar** [sahirbhatnagar/casebase#92]
I'm not sure if this was on purpose, but `ci` is not passed to the predict function. If we're going to use the `estimate_hazard` method for plotting as well, it would be ideal to have the `ci` (for `glm` and `gam`):

https://github.com/sahirbhatnagar/casebase/blob/249c6b0c318da0a0a6df21335c7dbc7fb2206755/R/hazard_estimation.R#L16

**Comment by turgeonmaxime** [comment]
Yes and no. I created `hazard_estimation` with the intent of using it for `plotHazard`, and so that's why I have those arguments. But so far I've only used it for `absoluteRisk`, and for that I didn't need the confidence intervals, so that's why I'm not passing `ci` to any other functions. But it should be an easy fix, it shouldn't really break anything.
